general:
  debug: true
  production: false
network:
  forcehttp: true
  fqdn: localhost
  port: 8080
  ssl:
    allowselfsigned: true
    certificatepath: /etc/packagelock/ssl/cert.pem
    privatekeypath: /etc/packagelock/ssl/privkey.pem
