general:
  debug: true
  production: true
network:
  forcehttp: true
  fqdn: 0.0.0.0
  port: 8080
  ssl:
    allowselfsigned: true
    certificatepath: ./certs/testing.crt
    privatekeypath: ./certs/testing.key
