name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: ["created"]

jobs:
  build:
    runs-on: golang_latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag PackageLock:$(date +%s)
