name: Nightly Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  release:
    name: Create Nightly Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: devel

      - name: Set APP_VERSION
        id: version
        run: |
          VERSION="unstable"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Go Application
        run: |
          APP_VERSION=${{ env.APP_VERSION }}
          CGO_ENABLED=0 GOOS=linux go build -ldflags "-X 'main.AppVersion=$APP_VERSION'" -o packagelock

      - name: Create Release Archive
        run: |
          mkdir -p release
          mv packagelock release/
          tar -czvf release/packagelock-${{ env.APP_VERSION }}-linux-amd64-nightly.tar.gz -C release packagelock

      - name: Calculate Checksum
        run: |
          md5sum release/packagelock-${{ env.APP_VERSION }}-linux-amd64-nightly.tar.gz | cut -f1 -d' ' > release/packagelock-${{ env.APP_VERSION }}-linux-amd64-nightly.tar.gz.md5

      - name: Upload Assets to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload 180504390 \
            release/packagelock-${{ env.APP_VERSION }}-linux-amd64-nightly.tar.gz \
            release/packagelock-${{ env.APP_VERSION }}-linux-amd64-nightly.tar.gz.md5 \
            --clobber
