name: Upload Go test results

on:
    pull_request:
      branches:
        - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Installing dependencies
        run: go get .
      - name: Building Package
        run: go build -tags *